In [1]:
import fitz

pdf_path = "../data/fta-us/21-07CustomsAdmin_kor.pdf"

doc = fitz.open(pdf_path)

all_text = ""

for page in doc:
    all_text += page.get_text()

print(all_text[:5000])

제
7
장
관세행정및무역원활화
제7.1 조
공
표
1.
각당사국은자국의관세법, 규정및일반행정절차를, 인터넷상을
포함하여, 공표한다.
2.
각당사국은관세사안에관한이해관계인의질의를다루는하나이상의
질의처를지정하거나유지하며, 그러한질의절차에대한정보를인터넷상에서
이용가능하도록한다.
3.
가능한한도에서, 각당사국은자국이채택하고자하는관세사안을
규율하는일반적으로적용되는규정을미리공표하고, 이를채택하기에앞서
이해관계인에게의견을제시할수있는기회를제공한다.
제7.2 조
상품의반출
1.
양자간무역을원활화하기위하여, 각당사국은상품의효율적인반출을
위한간소화된통관절차를채택하거나유지한다.
2.
제1항에따라, 각당사국은자국세관당국또는그밖의권한있는당국이
다음의절차를채택하거나유지하도록보장한다.
가. 자국관세법의준수를보장하는데요구되는기간을넘지아니하는
기간내에, 그리고가능한한도에서상품의도착후48시간이내에,
상품을반출하게하는절차
나. 도착시에상품을반출하기위하여상품이도착하기전에통관정보가
전자적으로제출되고처리되도록하는절차
다. 창고또는그밖의시설로일시적으로이동시키지아니하고도착
지점에서상품이반출되도록허용하는절차, 그리고
라. 적용가능한관세․조세및수수료에대하여자국세관당국이최종
결정을내리기전에, 그리고그러한결정을저해함이없이, 수입자가
상품을세관으로부터반출할수있도록허용하는절차1)
제7.3 조
자동화
각당사국은상품의반출을위한절차를신속하게하는정보기술을활용하고,
가. 전자시스템이세관사용자에게접근가능하도록한다.
나. 국제표준을사용하도록노력한다.
다. 국제무역데이터의양자간교환을원활히하기위하여다른쪽당사국의
시스템과호환가능한전자시스템을개발하도록노력한다. 그리고
라. 세계관세기구의관세데이터모델과세계관세기구의관련권고사항및
지침에따라일련의공통적인데이터요소와처리절차를개발하도록
노력한다.
제7.4 조
위험관리
각당사국은자국세관당국이검사활동을고위험상품에집중할수있도록
하고저위험상품의통관및이동을간소화하는평가및선별을위한전자또는
자동화된위험관리시스템을채택하거나유지한다.
제7.5 조
협
력
1.
이협정의효과적인운영을원활히하기위하여, 각당사국은이협정의
1) 당사국은수입자가상품의수입과관련하여자국세관당국이최종적으로적용하는관세․조세및수수료의
지급액을충당하기에충분한담보․예치또는그밖의적절한증서의형태로보증을제공하도록요구할
수있다.
운영에실질적으로영향을미칠가능성이있는행정정책의중요한수정이나
수입을규율하는자국의법또는규정에관련된그밖의유사한진행사항에대한
사전통보를다른쪽당사국에게제공하도록노력한다.
2.
양당사국은다음에관한각당사국의법및규정의준수를달성하는데
협력한다.
가. 특혜관세대우의신청, 특혜관세대우신청절차및검증절차를포함하여,
수입또는수출을규율하는이협정의규정의이행및운영
나. 관세평가협정의이행및운영
다. 수입또는수출에대한제한또는금지, 그리고
라. 양당사국이합의할수있는그밖의관세사안
3.
당사국이수입을규율하는자국의법또는규정에관련된불법행위에
대하여합리적인의심을가지는경우, 그당사국은다른쪽당사국이상품의
수입과관련하여통상적으로수집된특정한비밀정보를제공할것을요청할수
있다.
4.
제3항에따른당사국의요청은서면으로이루어지며, 그정보를요청하는
목적을명시하고, 다른쪽당사국이그정보를찾아서이를제공할수있도록
충분히특정하여요청하는정보를적시한다.
5.
정보의요청을받은당사국은자국법과자국이당사국인관련국제
협정에따라그정보를담은서면답신을제공한다.
6.
제3항의목적상, 불법행위에대한합리적인의심이라함은공적또는
사적인출처로부터획득한관련사실정보를기초로한의심을말하며, 그사실
정보는다음중하나이상을포함한다.
가. 수입자또는수출자가수입을규율하는법또는규정을준수하지
아니하였다는전력
나. 제조자, 생산자또는어느한쪽당사국의영역으로부터다른쪽
당사국의영역으로의상품이동에관여한그밖의인이수입을규율
하는법또는규정을준수하지아니하였다는전력
다. 특정제품분야에서어느한쪽당사국의영역으로부터다른쪽
당사국의영역으로의상품의이동에관여한일부또는모든인이수입을
규율하는당사국의법또는규정을준수하지아니하였다는전력, 또는
라. 정보의요청당사국과요청을받은당사국이특정한요청의맥락에서
충분하다고합의하는그밖의정보
7.
각당사국은다른쪽당사국영역으로부터의수입품또는다른쪽당사국
영역으로의수출품이수입을규율하는다른쪽당사국의법또는규정, 특히
밀수및유사한위반을포함한불법행위에관련된법또는규정을준수하는지
여부를다른쪽당사국이판정하는데도움을줄그밖의정보를다른쪽
당사국에게제공하도록노력한다.
8.
양자간무역을원활화하기위하여, 각당사국은위험관리기법을개선하고,
국제공급망표준의이행을원활하게하며, 상품의시의적절하고효율적인통관을
위한절차를간소화하고제고하며, 직원의기술숙련을향상시키고, 수입을
규율하는당사국의법또는규정의준수를개선할수있는기술의사용을제고할
수있도록기술적자문및지원을다른쪽당사국에게제공하도록노력한다.
9.
양당사국은공동훈련프로그램을수행하고관세분석기술에관한
정보를교환하도록노력한다.
10. 양당사국은수입을규율하는각당사국의규정집행능력을제고하도록
노력한다. 양당사국은더나아가, 신속하고안전하게정보를교환하는데도움이
될접촉선의설치를포함한의사소통채널을마련하고유지하며수입문제에대한
양자간조정을개선하도록노력한다.
제7.6 조
비밀유지
1.
이장에따라다른쪽당사국에게정보를제공하는당사국이그정보를
비밀로지정하는경우, 그다른쪽당사국은그정보를비밀로유지한다. 정보를
제공하는당사국은그정보가비밀로유지될것이며다른쪽당사국이정보
요청에명시한목적으로만이용될것이고그정보를제공한당사국또는그
당사국에게정보를제공한인의명시적허락없이는공개되지아니할것임을
다른쪽당사국에게서면으로보장하라고요구할수있다.
2.
당사국이제1항에따라비밀로지정된정보를접수한경우에도, 그정보를
접수한당사국은법집행의목적상또는사법절차과정에서그정보를이용
하거나공개할수있다.
3.
당사국은다른쪽당사국이제1항에합치되게행동하지못하였을경우
그당사국이요청한정보를제공하는것을거부할수있다.
4.
각당사국은공개되면그정보를제공한인의경쟁적지위를저해할수
있는정보를포함하여그당사국의관세법행정에따라제출된비밀정보를
무단공개로부터보호하는절차를채택하거나유지한다.
제7.7 조
특송화물
각당사국은적절한통관통제및선별을유지하면서특송화물을위한
신속한통관절차를채택하거나유지한다. 이러한절차는
가. 특송화물을위하여별도의신속한통관절차를규정한다.
나. 특송화물이도착하기전에그화물의반출에필요한정보가전자적
으로제출되고처리되도록규정한다.
다. 가능하다면전자적수단을통하여, 특송화물에포함된모든상품을
적용대상으로하는단일적하목록의제출을허용한다.
라. 가능한한도에서, 특정상품이최소한의서류로통관되도록규정한다.
마. 통상적인상황하에서, 화물이도착한경우, 필요한통관서류가제출
된후4시간이내에특송화물이통관되도록규정한다.
바. 특송화물의중량또는관세가격에관계없이적용된다. 그리고
사. 통상적인상황하에서, 미화200달러이하특송화물의경우관세또는
세금이부과되지아니할것이고공식적인반입서류도요구되지아니할
것임을규정한다.2)
2) 사호에도불구하고, 당사국은특송화물이항공화물운송장이나그밖의선하증권을수반하도록요구할
제7.8 조
재심및불복청구
각당사국은관세사안에대한자국의결정에대하여자국영역에있는
수입자가다음에접근할수있도록보장한다.
가. 그결정을내린직원또는부서로부터독립된행정적재심3), 그리고
나. 그결정에대한사법적재심
보다명확히하기위하여, 각당사국은수출자또는생산자가재심을실시
하는당사국에게정보를직접제공할수있도록그리고그당사국이그정보를
제7.6조제4항에따라비밀로취급할것을요청할수있도록허용한다.
제7.9 조
벌
칙
각당사국은이협정에따른품목분류․관세평가․원산지국가및특혜대우
신청을규율하는것을포함한자국의관세법및규정의위반에대하여민사상
또는행정상의벌칙, 그리고적절한경우형사상의제재를부과할수있도록
하는조치를채택하거나유지한다.
제7.10 조
사전심사결정
1.
각당사국은, 자국영역에있는수입자나다른쪽당사국영역에있는
수출자또는생산자의서면요청이있는경우4), 자국영역으로상품이수입되기
전에자국의세관당국을통하여다음에대한사전심사결정서를발급한다.
가. 품목분류
수있다. 보다명확히하기위하여, 당사국은수입제한상품에대하여관세또는세금을부과할수있고
공식적인반입서류를요구할수있다.
3) 대한민국의경우, 가호에따른행정적재심은대한민국국세심판원의심판을포함할수있다.
4) 보다명확히하기위하여, 수입자․수출자또는생산자는정당하게권한을받은대표자를통하여사전
심사신청을제출할수있다.
나. 관세평가협정에따라특정한사안에대한관세평가기준의적용
다. 관세환급, 납기연장또는그밖의관세감면의적용
라. 상품이원산지상품인지여부
마. 수리또는개조를위하여다른쪽당사국의영역으로수출된후어느
한쪽당사국의영역으로재반입된상품이제2.6조(수리또는개조후
재반입되는상품)에따라무관세대우를받을자격이있는지여부
바. 원산지국가표시
사. 상품이쿼터나관세율할당의적용을받는지여부, 그리고
아. 양당사국이합의하는그밖의사안
2.
각당사국은자국세관당국이요청을접수한후90일이내에사전심사
결정을발급한다. 다만, 신청인은당사국이요구하는경우사전심사결정을신청
하는상품의견본을포함하여당사국이요구하는모든정보를제출하여야한다.
사전심사결정을발급할때, 그당사국은신청인이제공한사실및상황을고려
한다. 보다명확히하기위하여, 당사국은사전심사결정의근거가되는사실과
상황이행정적또는사법적재심의대상이되는경우사전심사결정의발급을
거부할수있다. 이항에따라사전심사결정의발급을거부하는당사국은사전
심사결정의발급거부결정에관한관련사실및근거를적시하여신청인에게
서면으로신속하게통보한다.
3.
각당사국은사전심사결정의근거가되는사실또는상황에변동이없는
경우에한하여사전심사결정이발급된날또는사전심사결정에명시된다른날
로부터사전심사결정이효력이발생하도록규정한다.
4.
발급당사국은신청인에게통보한후사전심사결정을변경하거나철회할
수있다. 발급당사국은사전심사결정이부정확한정보또는허위의정보에기초
하였던경우에한해서만사전심사결정을소급하여변경하거나철회할수있다.
5.
각당사국은신청인에게사전심사결정의행정적재심에대한접근을보장
한다.
6.
자국법의비밀유지요건을조건으로, 각당사국은자국의사전심사결정을,
인터넷상을포함하여, 공표한다.
7.
신청인이허위의정보를제공하거나사전심사결정에관한관련사실또는
상황을누락하는경우또는사전심사결정의조건에따라행동하지아니하는경우,
수입당사국은민사․형사및행정적조치, 금전상의벌칙, 또는그밖의제재를
포함한적절한조치를적용할수있다.

In [2]:
lines = all_text.split("\n")

for i in range(200):
    print(repr(lines[i]))

'제'
'7'
'장'
'관세행정및무역원활화'
'제7.1 조'
'공'
'표'
'1.'
'각당사국은자국의관세법, 규정및일반행정절차를, 인터넷상을'
'포함하여, 공표한다.'
'2.'
'각당사국은관세사안에관한이해관계인의질의를다루는하나이상의'
'질의처를지정하거나유지하며, 그러한질의절차에대한정보를인터넷상에서'
'이용가능하도록한다.'
'3.'
'가능한한도에서, 각당사국은자국이채택하고자하는관세사안을'
'규율하는일반적으로적용되는규정을미리공표하고, 이를채택하기에앞서'
'이해관계인에게의견을제시할수있는기회를제공한다.'
'제7.2 조'
'상품의반출'
'1.'
'양자간무역을원활화하기위하여, 각당사국은상품의효율적인반출을'
'위한간소화된통관절차를채택하거나유지한다.'
'2.'
'제1항에따라, 각당사국은자국세관당국또는그밖의권한있는당국이'
'다음의절차를채택하거나유지하도록보장한다.'
'가. 자국관세법의준수를보장하는데요구되는기간을넘지아니하는'
'기간내에, 그리고가능한한도에서상품의도착후48시간이내에,'
'상품을반출하게하는절차'
'나. 도착시에상품을반출하기위하여상품이도착하기전에통관정보가'
'전자적으로제출되고처리되도록하는절차'
'다. 창고또는그밖의시설로일시적으로이동시키지아니하고도착'
'지점에서상품이반출되도록허용하는절차, 그리고'
'라. 적용가능한관세․조세및수수료에대하여자국세관당국이최종'
'결정을내리기전에, 그리고그러한결정을저해함이없이, 수입자가'
'상품을세관으로부터반출할수있도록허용하는절차1)'
'제7.3 조'
'자동화'
'각당사국은상품의반출을위한절차를신속하게하는정보기술을활용하고,'
'가. 전자시스템이세관사용자에게접근가능하도록한다.'
'나. 국제표준을사용하도록노력한다.'
'다. 국제무역데이터의양자간교환을원활히하기위하여다른쪽당사국의'
'시스템과호환가능한전자시스템을개발하도록노력한다. 그리고'
'라. 세계관세기구의관세데이터모델과세계관세기구의관련권고사항및'
'지침에따라일련의공통적인데이터요소와처리절차를개발하도록'
'노력한다.'
'제7.4 조'
'위험관리'
'각당사국은자국세관당국이검사활동을고위험상품에집중할수있도록'
'하고저위험상품의통관및이동을간소화하는평가및선별을위한전자또는'
'자동화된위험관리시스템을채택하거나유지한다.'
'제7.5 조'
'협'
'력'
'1.'
'이협정의효과적인운영을원활히하기위하여, 각당사국은이협정의'
'1) 당사국은수입자가상품의수입과관련하여자국세관당국이최종적으로적용하는관세․조세및수수료의'
'지급액을충당하기에충분한담보․예치또는그밖의적절한증서의형태로보증을제공하도록요구할'
'수있다.'
'운영에실질적으로영향을미칠가능성이있는행정정책의중요한수정이나'
'수입을규율하는자국의법또는규정에관련된그밖의유사한진행사항에대한'
'사전통보를다른쪽당사국에게제공하도록노력한다.'
'2.'
'양당사국은다음에관한각당사국의법및규정의준수를달성하는데'
'협력한다.'
'가. 특혜관세대우의신청, 특혜관세대우신청절차및검증절차를포함하여,'
'수입또는수출을규율하는이협정의규정의이행및운영'
'나. 관세평가협정의이행및운영'
'다. 수입또는수출에대한제한또는금지, 그리고'
'라. 양당사국이합의할수있는그밖의관세사안'
'3.'
'당사국이수입을규율하는자국의법또는규정에관련된불법행위에'
'대하여합리적인의심을가지는경우, 그당사국은다른쪽당사국이상품의'
'수입과관련하여통상적으로수집된특정한비밀정보를제공할것을요청할수'
'있다.'
'4.'
'제3항에따른당사국의요청은서면으로이루어지며, 그정보를요청하는'
'목적을명시하고, 다른쪽당사국이그정보를찾아서이를제공할수있도록'
'충분히특정하여요청하는정보를적시한다.'
'5.'
'정보의요청을받은당사국은자국법과자국이당사국인관련국제'
'협정에따라그정보를담은서면답신을제공한다.'
'6.'
'제3항의목적상, 불법행위에대한합리적인의심이라함은공적또는'
'사적인출처로부터획득한관련사실정보를기초로한의심을말하며, 그사실'
'정보는다음중하나이상을포함한다.'
'가. 수입자또는수출자가수입을규율하는법또는규정을준수하지'
'아니하였다는전력'
'나. 제조자, 생산자또는어느한쪽당사국의영역으로부터다른쪽'
'당사국의영역으로의상품이동에관여한그밖의인이수입을규율'
'하는법또는규정을준수하지아니하였다는전력'
'다. 특정제품분야에서어느한쪽당사국의영역으로부터다른쪽'
'당사국의영역으로의상품의이동에관여한일부또는모든인이수입을'
'규율하는당사국의법또는규정을준수하지아니하였다는전력, 또는'
'라. 정보의요청당사국과요청을받은당사국이특정한요청의맥락에서'
'충분하다고합의하는그밖의정보'
'7.'
'각당사국은다른쪽당사국영역으로부터의수입품또는다른쪽당사국'
'영역으로의수출품이수입을규율하는다른쪽당사국의법또는규정, 특히'
'밀수및유사한위반을포함한불법행위에관련된법또는규정을준수하는지'
'여부를다른쪽당사국이판정하는데도움을줄그밖의정보를다른쪽'
'당사국에게제공하도록노력한다.'
'8.'
'양자간무역을원활화하기위하여, 각당사국은위험관리기법을개선하고,'
'국제공급망표준의이행을원활하게하며, 상품의시의적절하고효율적인통관을'
'위한절차를간소화하고제고하며, 직원의기술숙련을향상시키고, 수입을'
'규율하는당사국의법또는규정의준수를개선할수있는기술의사용을제고할'
'수있도록기술적자문및지원을다른쪽당사국에게제공하도록노력한다.'
'9.'
'양당사국은공동훈련프로그램을수행하고관세분석기술에관한'
'정보를교환하도록노력한다.'
'10. 양당사국은수입을규율하는각당사국의규정집행능력을제고하도록'
'노력한다. 양당사국은더나아가, 신속하고안전하게정보를교환하는데도움이'
'될접촉선의설치를포함한의사소통채널을마련하고유지하며수입문제에대한'
'양자간조정을개선하도록노력한다.'
'제7.6 조'
'비밀유지'
'1.'
'이장에따라다른쪽당사국에게정보를제공하는당사국이그정보를'
'비밀로지정하는경우, 그다른쪽당사국은그정보를비밀로유지한다. 정보를'
'제공하는당사국은그정보가비밀로유지될것이며다른쪽당사국이정보'
'요청에명시한목적으로만이용될것이고그정보를제공한당사국또는그'
'당사국에게정보를제공한인의명시적허락없이는공개되지아니할것임을'
'다른쪽당사국에게서면으로보장하라고요구할수있다.'
'2.'
'당사국이제1항에따라비밀로지정된정보를접수한경우에도, 그정보를'
'접수한당사국은법집행의목적상또는사법절차과정에서그정보를이용'
'하거나공개할수있다.'
'3.'
'당사국은다른쪽당사국이제1항에합치되게행동하지못하였을경우'
'그당사국이요청한정보를제공하는것을거부할수있다.'
'4.'
'각당사국은공개되면그정보를제공한인의경쟁적지위를저해할수'
'있는정보를포함하여그당사국의관세법행정에따라제출된비밀정보를'
'무단공개로부터보호하는절차를채택하거나유지한다.'
'제7.7 조'
'특송화물'
'각당사국은적절한통관통제및선별을유지하면서특송화물을위한'
'신속한통관절차를채택하거나유지한다. 이러한절차는'
'가. 특송화물을위하여별도의신속한통관절차를규정한다.'
'나. 특송화물이도착하기전에그화물의반출에필요한정보가전자적'
'으로제출되고처리되도록규정한다.'
'다. 가능하다면전자적수단을통하여, 특송화물에포함된모든상품을'
'적용대상으로하는단일적하목록의제출을허용한다.'
'라. 가능한한도에서, 특정상품이최소한의서류로통관되도록규정한다.'
'마. 통상적인상황하에서, 화물이도착한경우, 필요한통관서류가제출'
'된후4시간이내에특송화물이통관되도록규정한다.'
'바. 특송화물의중량또는관세가격에관계없이적용된다. 그리고'
'사. 통상적인상황하에서, 미화200달러이하특송화물의경우관세또는'
'세금이부과되지아니할것이고공식적인반입서류도요구되지아니할'
'것임을규정한다.2)'
'2) 사호에도불구하고, 당사국은특송화물이항공화물운송장이나그밖의선하증권을수반하도록요구할'
'제7.8 조'
'재심및불복청구'
'각당사국은관세사안에대한자국의결정에대하여자국영역에있는'
'수입자가다음에접근할수있도록보장한다.'
'가. 그결정을내린직원또는부서로부터독립된행정적재심3), 그리고'
'나. 그결정에대한사법적재심'
'보다명확히하기위하여, 각당사국은수출자또는생산자가재심을실시'
'하는당사국에게정보를직접제공할수있도록그리고그당사국이그정보를'
'제7.6조제4항에따라비밀로취급할것을요청할수있도록허용한다.'
'제7.9 조'
'벌'
'칙'
'각당사국은이협정에따른품목분류․관세평가․원산지국가및특혜대우'
'신청을규율하는것을포함한자국의관세법및규정의위반에대하여민사상'
'또는행정상의벌칙, 그리고적절한경우형사상의제재를부과할수있도록'
'하는조치를채택하거나유지한다.'
'제7.10 조'
'사전심사결정'
'1.'
'각당사국은, 자국영역에있는수입자나다른쪽당사국영역에있는'
'수출자또는생산자의서면요청이있는경우4), 자국영역으로상품이수입되기'
'전에자국의세관당국을통하여다음에대한사전심사결정서를발급한다.'
'가. 품목분류'
'수있다. 보다명확히하기위하여, 당사국은수입제한상품에대하여관세또는세금을부과할수있고'
'공식적인반입서류를요구할수있다.'
'3) 대한민국의경우, 가호에따른행정적재심은대한민국국세심판원의심판을포함할수있다.'
'4) 보다명확히하기위하여, 수입자․수출자또는생산자는정당하게권한을받은대표자를통하여사전'
'심사신청을제출할수있다.'
'나. 관세평가협정에따라특정한사안에대한관세평가기준의적용'
'다. 관세환급, 납기연장또는그밖의관세감면의적용'
'라. 상품이원산지상품인지여부'
'마. 수리또는개조를위하여다른쪽당사국의영역으로수출된후어느'
'한쪽당사국의영역으로재반입된상품이제2.6조(수리또는개조후'
'재반입되는상품)에따라무관세대우를받을자격이있는지여부'
'바. 원산지국가표시'
'사. 상품이쿼터나관세율할당의적용을받는지여부, 그리고'
'아. 양당사국이합의하는그밖의사안'
'2.'
'각당사국은자국세관당국이요청을접수한후90일이내에사전심사'
'결정을발급한다. 다만, 신청인은당사국이요구하는경우사전심사결정을신청'
'하는상품의견본을포함하여당사국이요구하는모든정보를제출하여야한다.'
'사전심사결정을발급할때, 그당사국은신청인이제공한사실및상황을고려'
'한다. 보다명확히하기위하여, 당사국은사전심사결정의근거가되는사실과'
'상황이행정적또는사법적재심의대상이되는경우사전심사결정의발급을'
'거부할수있다. 이항에따라사전심사결정의발급을거부하는당사국은사전'
'심사결정의발급거부결정에관한관련사실및근거를적시하여신청인에게'
'서면으로신속하게통보한다.'
'3.'

In [4]:
import re

articles = []

for i, line in enumerate(lines):

    line = line.strip()

    if re.match(r'^제\d+\.\d+\s*조$', line):
        articles.append((i, line))

print("조문 수:", len(articles))
articles[:10]

조문 수: 10

[(4, '제7.1 조'),
 (18, '제7.2 조'),
 (36, '제7.3 조'),
 (46, '제7.4 조'),
 (51, '제7.5 조'),
 (115, '제7.6 조'),
 (135, '제7.7 조'),
 (152, '제7.8 조'),
 (161, '제7.9 조'),
 (168, '제7.10 조')]

In [7]:
# 청킹

chunks = []

for idx in range(len(articles)):

    start = articles[idx][0]

    article = articles[idx][1]

    # 제목
    title = lines[start + 1].strip()

    # 다음 조문 위치
    if idx < len(articles) - 1:
        end = articles[idx + 1][0]
    else:
        end = len(lines)

    content = "\n".join(lines[start:end])

    chunks.append({
        "agreement": "KR_CN_FTA",
        "chapter": "통관절차 및 무역원활화",
        "article": article,
        "title": title,
        "content": content
    })

print("청크 수:", len(chunks))
print(chunks[0])

청크 수: 10
{'agreement': 'KR_CN_FTA', 'chapter': '통관절차 및 무역원활화', 'article': '제7.1 조', 'title': '공', 'content': '제7.1 조\n공\n표\n1.\n각당사국은자국의관세법, 규정및일반행정절차를, 인터넷상을\n포함하여, 공표한다.\n2.\n각당사국은관세사안에관한이해관계인의질의를다루는하나이상의\n질의처를지정하거나유지하며, 그러한질의절차에대한정보를인터넷상에서\n이용가능하도록한다.\n3.\n가능한한도에서, 각당사국은자국이채택하고자하는관세사안을\n규율하는일반적으로적용되는규정을미리공표하고, 이를채택하기에앞서\n이해관계인에게의견을제시할수있는기회를제공한다.'}

In [8]:
import pandas as pd

df = pd.DataFrame(chunks)

df.head()

,agreement,chapter,article,title,content
0,KR_CN_FTA,통관절차 및 무역원활화,제7.1 조,공,"제7.1 조\n공\n표\n1.\n각당사국은자국의관세법, 규정및일반행정절차를, 인터넷..."
1,KR_CN_FTA,통관절차 및 무역원활화,제7.2 조,상품의반출,"제7.2 조\n상품의반출\n1.\n양자간무역을원활화하기위하여, 각당사국은상품의효율적..."
2,KR_CN_FTA,통관절차 및 무역원활화,제7.3 조,자동화,"제7.3 조\n자동화\n각당사국은상품의반출을위한절차를신속하게하는정보기술을활용하고,\..."
3,KR_CN_FTA,통관절차 및 무역원활화,제7.4 조,위험관리,제7.4 조\n위험관리\n각당사국은자국세관당국이검사활동을고위험상품에집중할수있도록\n...
4,KR_CN_FTA,통관절차 및 무역원활화,제7.5 조,협,"제7.5 조\n협\n력\n1.\n이협정의효과적인운영을원활히하기위하여, 각당사국은이협..."

In [11]:
df.to_csv(
    "../output/kr_us_customs_facilitation.csv",
    index=False,
    encoding="utf-8-sig"
)

print("저장 완료")

저장 완료

In [16]:
import fitz

pdf_path = "../data/fta-cn/CH_4_Customs_Procedures_and_Trade_Facilitation_KC_rev_kor.pdf"

doc = fitz.open(pdf_path)

all_text = ""

for page in doc:
    all_text += page.get_text()

print(all_text[:5000])

42

제4장
통관 절차 및 무역원활화


제4.1조
정의

이 장의 목적상,

관세법이란 상품의 수입, 수출, 이동 또는 보관, 관세당국에 구체적으로 위임된 행정 및
집행에 관한 법적이고 규제적인 규정, 그리고 법적으로 부여된 권한에 따라 관세당국이
제정한 모든 규제를 말한다.

통관 절차란 각 관세당국이 관세법의 대상이 되는 상품 및 운송 수단에 적용하는 취급을
말한다. 그리고

운송수단이란 인, 상품 또는 물품을 운송하여 당사국의 영역에 들어오거나 나가는 다양한
종류의 선박, 차량, 항공기 및 짐 싣는 동물을 말한다.


제4.2조
적용범위 및 목적

1.
이 장은, 양 당사국의 각각의 국제적 의무와 국내 관세법에 따라, 양 당사국 간
에 교역되는 상품 및 양 당사국 간 운송수단의 이동에 적용되는 통관 절차에 적용된다.

2.
이 장의 목적은 다음과 같다.

가.
양 당사국의 통관 절차의 간소화 및 조화

나.
양 당사국 간 무역의 원활화, 그리고

다.
이 장의 적용범위 내에서 관세당국 간 협력 증진


제4.3조
원활화

1.
각 당사국은 자국의 통관 절차와 관행이 무역을 원활화할 수 있도록 예측가능하
고, 일관성 있으며 투명할 것을 보장한다.

2.
가능한 경우 그리고 각국의 관세법에 의하여 허용되는 범위 내에서, 각 당사국의
통관 절차는, 개정된 것으로서 개정 교토협약으로 알려진 「세관절차의 간소화 및 조화에
관한 국제협약」의 문서들을 포함하여, 그 당사국이 체약당사자인 세계관세기구의 무역
관련 합의문서와 합치한다.

3.
관세당국은 자국의 통관 절차를 운용함에 있어 상품의 반출을 포함하여 통관을
원활하게 한다.

4.
각 당사국은 자국의 무역업자들이 상품의 반출을 포함하여 통관을 위하여 요구
43

되는 모든 규제정보를 제출할 수 있는 전자적 또는 그 밖의 방식의 단일창구를 제공하기
위하여 노력한다.


제4.4조
일관성

양 당사국은 가능한 범위 내에서 자국의 관세에 관한 법과 규정이 전국적으로 일관되게
이행되는 것을 보장하고, 적절한 조치를 수립 및 시행함으로써 자국의 지역 세관 간에
법과 규정의 이행과정에서 발생할 수 있는 비일관성 문제를 억지하기 위하여 노력한다.


제4.5조
투명성

1.
각 당사국은 자국의 관세 및 그 밖의 무역 관련 법, 규정, 일반적인 행정절차와
수수료 및 비용을 포함한 그 밖의 요건이 공식적인 웹사이트를 포함하여 공식적으로 지
정된 매체를 통하여 모든 이해당사자에게 용이하게 이용 가능하도록 보장한다. 각 관세
당국은 적용하거나 집행하는 모든 관세법 및 모든 행정절차를 공식적인 웹사이트를 포함
하여 공식적으로 지정된 매체를 통하여 공표한다.

2.
각 관세당국은 이 협정의 이행에서 발생하는 관세 사안에 관한 어느 한쪽 당사
국의 이해관계인의 질의를 다루는 하나 이상의 질의처를 지정하거나 유지하고, 그러한
질의 절차에 대한 정보를 공식적인 웹사이트 상에서 이용 가능하도록 한다.

3.
가능한 한도 내에서, 각 관세당국은 자신이 채택하고자 하는 관세 사안을 규율하
는 일반적으로 적용되는 새로운 또는 개정된 모든 규정을 미리 공표하고, 이를 채택하기
에 앞서 이해관계인에게 의견을 제시할 수 있는 기회를 제공한다.

4.
각 관세당국은 다른 쪽 관세당국에 이 장의 운영에 실질적으로 영향을 미칠 가
능성이 있는 상품의 이동 및 운송수단을 규율하는 관세 법 또는 절차에 관한 중요한 수
정에 대하여 시의적절하게 통지한다.


제4.6조
관세평가

양 당사국은 1994년도 GATT 제7조 및 관세평가협정의 규정에 따라 양 당사국 간 거
래되는 상품의 과세가격을 결정한다.


제4.7조
품목분류

양 당사국은 「통일상품명 및 부호체계에 관한 국제협약」을 양 당사국 간 교역되는 상품
에 적용한다.


제4.8조
관세협력
44


1.
양 당사국은 상품의 적법한 이동을 원활히 하기 위한 자국의 약속을 확인하고,
통관 기술 및 절차를 개선하기 위한 조치와 전산화 시스템에 관한 전문지식을 교환한다.

2.
자국 국내법에서 허용된 한도 내에서, 관세당국은 다음에 관하여 상호 지원한다.

가.
이 장의 이행 및 운영, 그리고

나.
양 당사국이 상호 결정하는 그 밖의 사안


제4.9조
재심 및 불복청구

1.
각 당사국은 수입자, 수출자 또는 자국의 결정에 영향을 받는 그 밖의 모든 인에
게 자국의 법과 규정에 따라 다음에 대하여 접근하도록 한다.

가.
재심 중에 있는 결정에 대하여 책임이 있는 공무원 또는 부서로부터 독
립된, 자국의 관세당국의 결정에 관한 한 단계의 행정적 재심, 그리고

나.
자국의 법과 규정에 따른 그 행정적 결정에 대한 사법적 재심

2.
재심 당국의 요청이 있는 경우, 생산자 또는 수출자는 행정적 재심을 수행하는
당사국에게 정보를 직접 제공하고, 그러한 당사국에 그 당사국에서 적용 가능한 규칙에
따라 그 정보를 비밀로 취급할 것을 요청할 수 있다. 이 정보는 양 당사국에 의하여 결
정된 규칙에 따라 제공된다.


제4.10조
사전심사

1.
각 당사국의 관세당국은 수입자, 수출자 또는 그 당사국1의 영역 내에 있는 그
밖의 모든 신청자의 서면 요청에 따라, 자국 영역으로 상품이 수입되기 전에, 사전심사
요청을 처리하는 데 필요한 정보의 상세설명을 포함하여 신청자에 의하여 제공된 사실
및 상황을 기반으로 서면 사전심사서를 발급한다. 사전심사서는 다음 사안에 대하여 발
급될 수 있다.

가.
품목분류

나.
이 협정에 따른 상품의 원산지, 그리고

다.
양 당사국이 합의할 수 있는 그 밖의 사안

2.
관세당국은, 신청자가 국내 법과 규정 및 규칙에 따라 요구되는 모든 정보를 제
출한 경우, 신청 후 90일 이내에 사전심사서를 발급한다. 사전심사는 그 결정의 근거가
된 사실 또는 상황에 변동이 없는 경우, 그 발급일부터 효력이 발생한다.

3.
효력이 발생한 사전심사는 다음과 같은 경우에 취소, 수정 또는 철회될 수 있다.

1 중국의 경우, 사전심사의 신청자는 중국 세관에 등록되어야 한다.
45



가.
사전심사 결정이 기반하는 정보가 거짓이거나 부정확하다는 점이 사실
또는 상황에 의하여 입증되는 경우. 이 경우, 관세당국은 신청자에 대하
여 자국의 국내 법에 따른 민사, 형사 및 행정적 조치, 벌칙 또는 그 밖
의 제재를 포함하는 적절한 조치를 적용할 수 있다.

나.
관세당국에 의한 명백한 오류로 인하여 원래의 사전심사와 동일한 사실
과 상황 하에서 관세당국이 다른 기준을 적용하는 것이 바람직하다고 보
는 경우. 이 경우, 개정 또는 철회는 그 변경이 있는 날부터 적용된다.
또는

다.
그 행정적 결정이 그 기반이 되는 법, 규정 및 규칙의 변화로 인하여 영
향을 받는 경우. 이 경우, 그 사전심사는 그러한 개정이 공표된 날부터
자동적으로 효력이 중단된다.

다호에 언급된 사안의 경우, 관세당국은 사전에 공표하는 것이 불가능한 경우를 제외하
고, 이해당사자가 고려할 수 있도록 그러한 개정이 효력을 발생하기 전에 충분한 시간을
두고, 검토된 정보를 이해당사자에게 이용 가능하게 한다.

4.
각 당사국은 자국의 법, 규정 및 규칙의 기밀유지 요건에 따라 자국의 사전심사
를 공표한다.

5.
당사국은 사전심사의 근거가 되는 사실 또는 상황이 행정적 또는 사법적 재심의
대상이 되는 경우 사전심사서의 발급을 거부할 수 있다.


제4.11조
벌칙

각 당사국은 이 협정에 따른 품목분류, 관세평가, 원산지 국가 및 특혜관세 대우 신청을
규율하는 것을 포함한 자국의 관세법 및 규정의 위반에 대하여 행정적 벌칙, 그리고 적
절한 경우 형사적 제재를 부과할 수 있도록 하는 조치를 채택하거나 유지한다.


제4.12조
자동화 시스템의 사용

관세당국은 세계관세기구 내 이 분야에서의 진전상황을 고려하여, 특히 종이 없는 무역
의 맥락에서, 비용 효과적이고 효율적인 경우 통관 운영을 지원하기 위하여 정보기술을
적용한다.


제4.13조
위험관리

1.
관세당국은 통관 절차를 운영함에 있어 통제 조치를 고위험 상품에 집중하고, 저
위험 상품의 통관을 원활히 한다.

2.
양 당사국은 국제무역 상의 자의적이거나 부당한 차별 또는 위장된 제한을 피하
는 방식으로 위험관리를 설계하고 적용한다.
46



제4.14조
상품의 반출

1.
각 당사국은 양 당사국 간 무역을 원활화하기 위하여 상품의 효율적인 반출을
위한 간소화된 통관절차를 채택하고 적용한다. 보다 명확히 하기 위하여, 이 항은 당사국
으로 하여금 반출을 위한 자국의 요건이 충족되지 아니한 상품의 반출을 요구하지 아니
한다.

2.
제1항에 따라, 각 당사국은 다음의 절차를 채택하거나 유지한다.

가.
특정 조건이나 요건의 충족을 전제로 가능한 한 도착시 상품을 반출하는
것이 가능하도록, 상품의 물리적 도착 전에 정보를 사전에 전자적으로
제출하고 처리하도록 규정하는 절차

나.
수입자가 충분하고 효과적인 보증을 제공하고 추가적인 조사, 물리적 검
사 또는 그 밖의 어떠한 제출이 요구되지 아니하는 경우 그 당사국의 모
든 수입요건이 충족되기 전에 수입자에게 상품의 반출을 허용할 수 있도
록 하는 절차

다.
자국 관세법 및 그 밖의 무역 관련 법과 절차의 준수를 보장하는데 요구
되는 기간을 넘지 아니하는 기간 내에, 그리고 가능한 한도 내에서 상품
의 도착 후 48시간 내에, 상품을 반출하게 하는 절차, 그리고

라.
금지, 통제 또는 규제되는 상품을 제외하고 상품을 보세창고 또는 그 밖
의 시설에 일시적으로 이동시키지 아니하고 세관 감시구역에서

In [17]:
lines = all_text.split("\n")

In [18]:
#cn-청킹

import re
articles = []

for i, line in enumerate(lines):

    line = line.strip()

    if re.match(r'^제\s*\d+\.\d+\s*조', line):
        articles.append((i, line))

print(len(articles))
print(articles[:5])

19
[(6, '제4.1조'), (22, '제4.2조'), (42, '제4.3조'), (67, '제4.4조'), (75, '제4.5조')]

In [19]:
chunks = []

for idx in range(len(articles)):

    start = articles[idx][0]

    article = articles[idx][1]

    # 제목
    title = lines[start + 1].strip()

    # 다음 조문 위치
    if idx < len(articles) - 1:
        end = articles[idx + 1][0]
    else:
        end = len(lines)

    content = "\n".join(lines[start:end])

    chunks.append({
        "agreement": "KOREA_CHINA_FTA",
        "chapter": "통관절차 및 무역원활화",
        "article": article,
        "title": title,
        "content": content
    })

print("청크 수:", len(chunks))
print(chunks[0])

청크 수: 19
{'agreement': 'KOREA_CHINA_FTA', 'chapter': '통관절차 및 무역원활화', 'article': '제4.1조', 'title': '정의', 'content': '제4.1조  \n정의 \n \n이 장의 목적상, \n \n관세법이란 상품의 수입, 수출, 이동 또는 보관, 관세당국에 구체적으로 위임된 행정 및 \n집행에 관한 법적이고 규제적인 규정, 그리고 법적으로 부여된 권한에 따라 관세당국이 \n제정한 모든 규제를 말한다. \n \n통관 절차란 각 관세당국이 관세법의 대상이 되는 상품 및 운송 수단에 적용하는 취급을 \n말한다. 그리고 \n \n운송수단이란 인, 상품 또는 물품을 운송하여 당사국의 영역에 들어오거나 나가는 다양한 \n종류의 선박, 차량, 항공기 및 짐 싣는 동물을 말한다. \n \n '}

In [20]:
for chunk in chunks[:3]:
    print("=" * 80)
    print(chunk["article"])
    print(chunk["title"])
    print(chunk["content"][:500])

================================================================================
제4.1조
정의
제4.1조
정의

이 장의 목적상,

관세법이란 상품의 수입, 수출, 이동 또는 보관, 관세당국에 구체적으로 위임된 행정 및
집행에 관한 법적이고 규제적인 규정, 그리고 법적으로 부여된 권한에 따라 관세당국이
제정한 모든 규제를 말한다.

통관 절차란 각 관세당국이 관세법의 대상이 되는 상품 및 운송 수단에 적용하는 취급을
말한다. 그리고

운송수단이란 인, 상품 또는 물품을 운송하여 당사국의 영역에 들어오거나 나가는 다양한
종류의 선박, 차량, 항공기 및 짐 싣는 동물을 말한다.


================================================================================
제4.2조
적용범위 및 목적
제4.2조
적용범위 및 목적

1.
이 장은, 양 당사국의 각각의 국제적 의무와 국내 관세법에 따라, 양 당사국 간
에 교역되는 상품 및 양 당사국 간 운송수단의 이동에 적용되는 통관 절차에 적용된다.

2.
이 장의 목적은 다음과 같다.

가.
양 당사국의 통관 절차의 간소화 및 조화

나.
양 당사국 간 무역의 원활화, 그리고

다.
이 장의 적용범위 내에서 관세당국 간 협력 증진


================================================================================
제4.3조
원활화
제4.3조
원활화

1.
각 당사국은 자국의 통관 절차와 관행이 무역을 원활화할 수 있도록 예측가능하
고, 일관성 있으며 투명할 것을 보장한다.

2.
가능한 경우 그리고 각국의 관세법에 의하여 허용되는 범위 내에서, 각 당사국의
통관 절차는, 개정된 것으로서 개정 교토협약으로 알려진 「세관절차의 간소화 및 조화에
관한 국제협약」의 문서들을 포함하여, 그 당사국이 체약당사자인 세계관세기구의 무역
관련 합의문서와 합치한다.

3.
관세당국은 자국의 통관 절차를 운용함에 있어 상품의 반출을 포함하여 통관을
원활하게 한다.

4.
각 당사국은 자국의 무역업자들이 상품의 반출을 포함하여 통관을 위하여 요구
43

되는 모든 규제정보를 제출할 수 있는 전자적 또는 그 밖의 방식의 단일창구를 제공하기
위하여 노력한다.

In [21]:

df = pd.DataFrame(chunks)

df.to_csv(
    "../output/kr_cn_customs_facilitation.csv",
    index=False,
    encoding="utf-8-sig"
)

print(df.shape)
df.head()

(19, 5)

,agreement,chapter,article,title,content
0,KOREA_CHINA_FTA,통관절차 및 무역원활화,제4.1조,정의,"제4.1조 \n정의 \n \n이 장의 목적상, \n \n관세법이란 상품의 수입, ..."
1,KOREA_CHINA_FTA,통관절차 및 무역원활화,제4.2조,적용범위 및 목적,"제4.2조 \n적용범위 및 목적 \n \n1. \n이 장은, 양 당사국의 각각..."
2,KOREA_CHINA_FTA,통관절차 및 무역원활화,제4.3조,원활화,제4.3조 \n원활화 \n \n1. \n각 당사국은 자국의 통관 절차와 관행이 ...
3,KOREA_CHINA_FTA,통관절차 및 무역원활화,제4.4조,일관성,제4.4조 \n일관성 \n \n양 당사국은 가능한 범위 내에서 자국의 관세에 관한...
4,KOREA_CHINA_FTA,통관절차 및 무역원활화,제4.5조,투명성,제4.5조 \n투명성 \n \n1. \n각 당사국은 자국의 관세 및 그 밖의 무...